### ISSUE TITLE
Compatibility problem

### ISSUE THREAD

**Issue by matiux** [el7cosmos/phpstorm-swoole-plugin#1]
I have a problem with

PhpStorm 2020.2 EAP
Build #PS-202.5103.20, built on June 4, 2020

```
Plugin 'Swoole IDE Helper' version 4.5.2 is incompatible with this installation: until build 201.SNAPSHOT < PS-202.5103.20
```

**Comment by el7cosmos** [comment]
Fixed in **4.5.3**

- https://github.com/el7cosmos/phpstorm-swoole-plugin/releases/tag/4.5.3 
- https://plugins.jetbrains.com/plugin/13040-swoole-ide-helper/versions/stable/95827

Thanks @matiux for reporting
