### ISSUE TITLE
Update to 5.0.0

### ISSUE THREAD

**Issue by Galaxy0419** [el7cosmos/phpstorm-swoole-plugin#59]
[Swoole 5.0.0](https://github.com/swoole/swoole-src/releases/tag/v5.0.0) was released two weeks ago.  Any plans to update this plugin to the latest version?

**Comment by el7cosmos** [comment]
v5 released
https://github.com/el7cosmos/phpstorm-swoole-plugin/releases/tag/5.0.0
https://plugins.jetbrains.com/plugin/13040-swoole-ide-helper/versions/stable/211403
